apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: k8/
    repoURL: https://github.com/AndyanaJ/final_project.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
