apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: andyanaj/todo:latest
        ports:
        - containerPort: 5000 
       # env:
       # - name: DB_USER
       #   value: root
       # - name: DB_PASSWORD
       #   value: root
       # - name: DB_HOST
       #  value: mysql
       # - name: DB_NAME
       #   value: flask
