apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7  # Use the desired MySQL version
        ports:
        - containerPort: 3306  # Default MySQL port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root  # Replace with your desired root password
        - name: MYSQL_DATABASE
          value: flask
        - name: MYSQL_USER
          value: flask
        - name: MYSQL_PASSWORD
          value: password
